### ISSUE TITLE
Language Selector: rapid language changes

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#115]
Sometimes when coming back to an old tab that has the dev site in it, I will change the language selector (not for the UI, one of the ones in a tool page) and it will rapidly change from one language to another, requiring me to refresh the page to get it to stop. I am not sure yet how to reproduce. My first thought is that there is a bug/race condition in the code that stores the state in `localStorage` and the code that loads the state to show the selector.

**Comment by elisabeth-sorrell** [comment]
Putting back into Todo for now
