### ISSUE TITLE
load test data

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#200]
We need an admin-only function that creates a bunch of data in the database. We need to be able to load up a test env with A LOT of data. Figure out an elegant pattern for creating lots of rows in all our tables.

**Comment by michaelmarshall** [comment]
I updated the ticket to not require only using the API. For perf reasons we may need to do a lot in a DB proc.

**Comment by elisabeth-sorrell** [comment]
- [x] Generate maps, pulling a specified amount from our datasets repo
- [x] Add translations for map words/phrases in a user-specified number of languages
- [x] Generate `${user_count}` users that vote on the added translations
- [x] Generate words/phrases not associated with map data
- [x] Generate specified number of words and/or phrases
- [x] Have a progress box that receives progress from the backend
- [ ] Functionality for user to cancel generation
