### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#22]
when a user clicks a discussion icon, they'll go to a new page that shows the headers of the sending page and the discussion box.

so if a user is on the dictionary word detail page for 'Israel' and they click on the discussion icon for the 'Israel' entry, the discussion box will show a header for 'Dictionary' and a sub header for 'Israel'

if they click on a word definition for 'Israel', the discussion page will show 'Dictionary', 'Israel', and the word definition in the header

![Screen Shot 2023-07-20 at 2 24 32 PM](https://github.com/etenlab/crowd.rocks/assets/1165460/9691d84e-41d6-4a3d-a0b7-30a61a897e10)

**Comment by elisabeth-sorrell** [comment]
@lucky-gru helping out with caching
