### ISSUE TITLE
Deadlock problem at reTranslation Method

### ISSUE THREAD

**Issue by lucky-gru** [etenlab/crowd.rocks#229]
![image](https://github.com/etenlab/crowd.rocks/assets/42648696/ef1f9c62-dbca-4769-afd4-3916ad7549c3)

Seems DB encounters a deadlock status.
plz look at the line 1410
https://github.com/etenlab/crowd.rocks/blob/translate-fire-and-forget/api/src/components/translations/translations.service.ts#L1348

![image](https://github.com/etenlab/crowd.rocks/assets/42648696/c65180da-b664-4ef3-87ac-5b8639ed0899)

**Comment by michaelmarshall** [comment]
we've removed this line and will trigger maps translations after a google run has finished.
