### ISSUE TITLE
Maps translation isn't releasing resources properly

### ISSUE THREAD

**Issue by elisabeth-sorrell** [etenlab/crowd.rocks#236]
1. Upload a map
2. a. Error is output: Cannot set property closed of Readable which only has a getter
3. Go to google translate page
4. Select a source and target, and translate all
5. go back to maps page
6. select same language as target from google translate
7. go to maps -> translate page
8. Nothing is displayed, won't output maps, site can't fetch any more data. Backend outputs same error and cannot recover. Google chrome inspect shows that `/graphql` endpoint is giving a `CONNECTION_REFUSED` error.

**Comment by ForeverYoung1208** [comment]
can't repeat error: at my local env map uploading doesn't produse any error (oncluding mentioned "Cannot set property closed of Readable which only has a getter"

![image](https://github.com/etenlab/crowd.rocks/assets/767556/4bc9a109-fe0f-46be-9b31-388805b465fa)

**Comment by ForeverYoung1208** [comment]
Anyway, i refactored the code to get rid of the library that trows your error.
