### ISSUE TITLE
Map Discussion and Voting

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#247]
Add a voting, flagging, and discussion icons/feature to the map detail view page. put the buttons above the map view. this will let users vote on the original/translated maps as well as discuss the maps themselves. this should be easy since those components exist, but you'll have to add db schema like other voting tables i think.

**Comment by ForeverYoung1208** [comment]
https://github.com/etenlab/crowd.rocks/pull/255
