### ISSUE TITLE
Lilt Integration

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#258]
use the [Lilt API](https://lilt.com/docs/api) to do the same thing that the google bot does. create a lilt bot user account for the new lilt bot to use. Update the AI Controller page with the new bot's functionality, should be just like the google bot.

We have a business account with Lilt but for now create a free account while I get us the real accounts we need. It may take a couple of days.

**Comment by ForeverYoung1208** [comment]
It is impossible to get free Lilt's account for me now (there is no automatical creation, and they haven't answered on my email yet).
So, i prepared all i could (it was necessary to make some refactoring):
https://github.com/etenlab/crowd.rocks/pull/265

Maybe, they will answer me and give some free account. Maybe, we will get real account earlier.
Anyway, i must get a possibility to test everything with account and then i can continue with this task.
