### ISSUE TITLE
API to get all maps

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#315]
work the same as #314 

make an API only endpoint to get all maps as a zip file. Issue #314 gives a per language button on the client, this ticket is just for an API to retrieve All maps as a zip.

**Comment by ForeverYoung1208** [comment]
Is i can understand, maps should be restricted by the language parameter, and it is mandatory. Otherwise, the size of the archive with all existing maps on all languages will be enormous.

**Comment by ForeverYoung1208** [comment]
@dinterr 
Need to update infrastructure:
- create s3 bucket `crowdrocks-public-files-dev-temp10min` with object lifetime 10 min (or 1 day if not possible to make lesser), after this timeout - permanently delete objects.
- add env variable `AWS_S3_TEMPORARY_BUCKET_NAME=crowdrocks-public-files-dev-temp10min`
