### ISSUE TITLE
Environment variables need to be added to prod and dev

### ISSUE THREAD

**Issue by elisabeth-sorrell** [etenlab/crowd.rocks#316]
OPENAI_API_KEY=[I can provide]
CR_GPT_3_PASSWORD={randomly generated password is fine}
CR_GPT_4_PASSWORD={randomly generated password is fine}

**Comment by ForeverYoung1208** [comment]
can you pls add also 

LILT_KEY=[I will provide later]

SMARTCAT_ID=[I will provide later]
SMARTCAT_KEY=[I will provide later]
SMARTCAT_PROFILE=[I will provide later]

DEEPL_KEY=[I will provide later]
