### ISSUE TITLE
add new languages to our library

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#339]
I'm not sure how, but we need to add languages to the bcp47 library we use (`language-tags`). these will be language subtags

Languages to add:
Senga
Fungwe
Lambya
Tambo
Wandya
Lungu
Kunda
Chikunda
Mukulu
Kabdende
Shila
Mwenyi
Liuwa

**Comment by ForeverYoung1208** [comment]
I've found that languages 

'Lambya' (lai)
'Kunda' (kdn)
'Mukulu' (moz)

already exist in the lib so i'll skip them.
