### ISSUE TITLE
Bug: new translation doesn't show unless page is refreshed

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#378]
Go to map translation, add a translation, view current translations. The new translation doesn't show. Refresh page. The new translation shows.

**Comment by ForeverYoung1208** [comment]
This bug can is present at the dev environment (https://dev.crowd.rocks/)
Bug doesn't appear in my local environment.

The bug: After adding new translation at the words list (sic! Not in the single word translation, only at word list)
i.e. here:

![Image](https://github.com/etenlab/crowd.rocks/assets/767556/80c7d9bb-2f21-464d-a88c-cd402cdff72c)


The new translation couldn't be found at the word translations here without manual page refresh


![Image](https://github.com/etenlab/crowd.rocks/assets/767556/156c6366-893a-4867-a385-15d81a07dec8)

Note: once (!)  i've got apollo's conslose error like 
`Unknown query named "GetTranslationsByFromDefinitionId" requested in refetchQueries options.include array`

**Comment by ForeverYoung1208** [comment]
Error can be repeated locally in case pre-building and serving application (like in production).

**Comment by ForeverYoung1208** [comment]
fixed by adding  fetchPolicy: 'no-cache'
