### ISSUE TITLE
Bug: have to refresh map translation list after adding translation.

### ISSUE THREAD

**Issue by elisabeth-sorrell** [etenlab/crowd.rocks#404]
Go to maps -> Translate all -> word/phrase detail -> add translation.
new translation isn't showing in list, hit refresh

**Comment by ForeverYoung1208** [comment]
now it goes infinie request cycle
![image](https://github.com/etenlab/crowd.rocks/assets/767556/7590169a-dde1-4c6a-ad45-c598053442d1)
