### ISSUE TITLE
Bug: voting in recommended map translation and map translation list isn't the same

### ISSUE THREAD

**Issue by elisabeth-sorrell** [etenlab/crowd.rocks#409]
- Upload a map
- go to translate all, see the translation list
- add a translation and vote on it
- refresh and go back to the map translation list, recommended translation that you voted on should show along with the source language text

- Go to AI Controller
- Google translate all to same target language
- go to map translation list
- you will see the recommended translation that google bot submitted.
- go to translation details
- the translation that the googlebot submitted doesn't show vote

**Comment by lucky-gru** [comment]
w
