### ISSUE TITLE
Ensure map translations make it into map

### ISSUE THREAD

**Issue by elisabeth-sorrell** [etenlab/crowd.rocks#419]
I thought I saw in prod a translation not appearing in maps, but it looked like it happened to some maps and not others. Need to make sure that's not happening

**Comment by ForeverYoung1208** [comment]
in order to investigate it we need exact case in the dev database (to check which exactly map and why glitches), 
theoretically, there may be just unsuitabe map structure.

**Comment by lucky-gru** [comment]
I remember it took a long time to create the map.
Ihor, you said it would take more than 6 hours before, right?
Maybe that's the problem?

**Comment by elisabeth-sorrell** [comment]
@ForeverYoung1208 
Here's a list in prod:

Translating to: Old Tamil
Phrase translated: 100 Kilometers
##Translation NOT found
Tyndale Gen-8_4.oty.cf.svg
Tyndale Is36-37.oty.cf.svg
Tyndale Jonah1.oty.cf.svg
Tyndale Gen-12_4.oty.cf.svg

##Translation found
Tyndale Ezra6_2.oty.cf.svg
Tyndale Neh2_9.oty.cf.svg

**Comment by ForeverYoung1208** [comment]
> I remember it took a long time to create the map. Ihor, you said it would take more than 6 hours before, right? Maybe that's the problem?

nonono, 6 hours had taken the translation of all maps to all nanguages.
Yes it is slow due to the process of dowloading the original, then translation, then uploading translated map to s3 bucket. But no so slow to take 6 hours for single map ))).
That's some enother issue, i'll investigate it.
