### ISSUE TITLE
Bug: Map translation list with Original_id does not get all data from server.

### ISSUE THREAD

**Issue by lucky-gru** [etenlab/crowd.rocks#435]
http://dev.crowd.rocks/US/en/1/maps/detail_view/3535?is_original=false

![Image](https://github.com/etenlab/crowd.rocks/assets/42648696/ad4c578f-dc9a-4b1d-b082-202831c0c8be)

http://dev.crowd.rocks/US/en/1/maps/translation/24

![Image](https://github.com/etenlab/crowd.rocks/assets/42648696/3a40ef77-956e-4426-84c3-189876b07cee)

only fetch those 6 translations

**Comment by ForeverYoung1208** [comment]
looks like the source of the problem is related to 
https://github.com/etenlab/crowd.rocks/issues/444

**Comment by ForeverYoung1208** [comment]
Looks like fixed.
