### ISSUE TITLE
Prod: investigate&fix failed map delete

### ISSUE THREAD

**Issue by elisabeth-sorrell** [etenlab/crowd.rocks#462]
please poke around the prod DB and see if you can see any anomalies between Biblica 01 (which should be deleted) and Biblica 02_03 (which should be normal).

**Comment by elisabeth-sorrell** [comment]
Biblica 02_03 is normal
Biblica 01 and Biblica 07_a have not successfully deleted all translated maps. 

Ihor has found that this is related to a vote issue and is going to put in a PR tomorrow, once that's patched/merged to prod we can proceed to delete the offending maps from UI and do a reupload.

**Comment by ForeverYoung1208** [comment]
https://github.com/etenlab/crowd.rocks/pull/463
I've done with it. I think this task can be closed after promoting  to prod.
