### ISSUE TITLE
Bug: error when adding an invalid target language for Lilt Translator

### ISSUE THREAD

**Issue by elisabeth-sorrell** [etenlab/crowd.rocks#520]
![Image](https://github.com/etenlab/crowd.rocks/assets/15220335/c68e2d97-d3cf-45f6-8e47-86912bf164f2)

I got this error in dev when using Lilt translator for Source=Japanese, Target=Arabic... Maybe we need some sort of guard in place in the AI Controller page if the source/target combination doesn't exist for the translator (maybe disable buttons or something).

**Comment by ForeverYoung1208** [comment]
Such a check existis - you can not translate from japanese to arabic using bot translation UI:
(If your source document is japanese, you can  select only available languages - english or chinese )


![Image](https://github.com/etenlab/crowd.rocks/assets/767556/a7f5a4aa-9d77-4a17-91c6-972f1d876cc1)

Can you please explain steps how can i reproduce your error?
