### ISSUE TITLE
language selector dialog UI tweaks

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#55]
<img width="701" alt="Screenshot 2023-08-08 at 9 15 56 PM" src="https://github.com/etenlab/crowd.rocks/assets/1165460/65f2cd6c-6921-4427-8bf8-5bac85c93031">

1. remove the checkboxes
2. remove the 'DONE' button
3. when a language is clicked, close the dialog
4. store the selection in `localStorage` as `target-language` (if you prefer another method or name ask me and explain)
5. when the dialog is opened, check `localStorage` and load the latest answer. show a checked mark or box to show the current answer.
6. update all current language input boxes (maps, site text) to check `localStorage` and load the saved language selection so that the user doesn't always have to input their language selection all the time when navigating around the site

**Comment by lucky-gru** [comment]
Fyi, at the frontend, we have an app context and related reducers, the app context data automatically persists at localStorage.
