### ISSUE TITLE
Super Tool > Source and Target languages are displayed incorrectly

### ISSUE THREAD

**Issue by iPiyushPatel** [etenlab/crowd.rocks#566]
**Steps to reproduce:**

  1. Login with valid-user
  2. Click on 'Super Tool'
  3. Select 'Source Language'
  4. Select 'Target Language'
  5. Click on the anyone document
  6. Verify the 'Source' and 'Target' languages

**Expected Result:**
- Source and Target languages should be displayed correctly

**Actual Result:**
- Source and Target languages are displayed incorrectly

**Attachments:**
See video:-

https://github.com/etenlab/crowd.rocks/assets/5212585/d8c646e1-d128-4392-aa07-9996359a37ca

CC: @michaelmarshall

**Comment by ForeverYoung1208** [comment]
should be solved with this PR
https://github.com/etenlab/crowd.rocks/pull/572

**Comment by iPiyushPatel** [comment]
> should be solved with this PR #572

Now, the issue is not replicating,
We can close this bug 

CC: @michaelmarshall
