### ISSUE TITLE
UX: button icon and placement change

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#591]
Change the button that brings down the tool menu to a hamburger menu icon and put the button at the top right instead of the bottom right like it is now.

<img width="845" alt="Screenshot 2023-12-14 at 3 32 50 PM" src="https://github.com/etenlab/crowd.rocks/assets/1165460/460e0af7-e88d-400c-91f2-a17fdbc9a16b">

**Comment by ForeverYoung1208** [comment]
also this button is sometimes hidded under the toolbox,
maybe place on the top of toolbox or change place

![Image](https://github.com/etenlab/crowd.rocks/assets/767556/9234bb80-b667-49fe-86b4-2c9a0174346a)
