### ISSUE TITLE
BUG: first pericope is not shown in translation view

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#592]
In the dev site in the lorem.txt file I created a pericope after an existing pericope and noticed on the translation page that the first pericope wasn't shown. The first pericope begins with 'Lorem' but in the translation view it begins with 'Tortor'.

<img width="821" alt="Screenshot 2023-12-14 at 3 42 03 PM" src="https://github.com/etenlab/crowd.rocks/assets/1165460/c251f1a5-d0e0-4ab4-a607-f6dc49528eb9">

<img width="927" alt="Screenshot 2023-12-14 at 3 41 03 PM" src="https://github.com/etenlab/crowd.rocks/assets/1165460/22f59079-be5a-40f9-bc84-207f213013d9">

**Comment by ForeverYoung1208** [comment]
There is no pericope starting from 'Lorem'.
Ah... maybe you mean that we always have to treat the beginning of the document as first pericope?

**Comment by ForeverYoung1208** [comment]
Maybe it is better to auto-create first starting pericope when new document added. It will be easier and more consistent with the rest of pericopes logic and tools.
