### ISSUE TITLE
add % complete on site language selector

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#65]
update language selector to optionally take some type of param so that we can display the % complete on the site text languages. as the site text data is downloaded once per refresh, we shouldn't need to store this data in the database, it can be determined via read query dynamically when called. ask Hiroshi for tips or knowledge transfers about how the site text schema works.

**Comment by elisabeth-sorrell** [comment]
@michaelmarshall Will circle back around to this when @lucky-gru is finished with site text refactor
